server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/EsmaNKilic/microserviceConfigServer
  profiles:
    active: dev












